#+bind: org-html-preamble-format (("en" "%d"))
#+OPTIONS: html-link-use-abs-url:nil html-postamble:t html-preamble:t
#+OPTIONS: html-scripts:t html-style:t html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+HTML_LINK_HOME: https://github.com/dieter-wilhelm/ansys-mode
#+HTML_LINK_UP: index.html
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:

#+STARTUP: showall
# #+title: INSTALLATION of APDL-Mode

Copyright (C) 2006 - 2025  H. Dieter Wilhelm, GPL V3

  Please install the [[https://www.gnu.org/software/emacs/][GNU-Emacs]] Editor first, for all functionality
  APDL-Mode requires version 25.1 (released in 2016) but its sources
  can be used with older versions (Emacs-24).  If you are new to this
  editor please check its tutorial in the `Help' menu, or read at
  least the APDL-Mode introduction.

* COMMENT Melpa Installation
  APDL-Mode is now available on the GNU-Emacs packages archive [[https://melpa.org/][Melpa]]
  for Emacs version 25.1 or newer.

  [[https://melpa.org/#/apdl-mode][file:https://melpa.org/packages/apdl-mode-badge.svg]]
  [[https://stable.melpa.org/#/apdl-mode][file:https://stable.melpa.org/packages/apdl-mode-badge.svg]]

  Please add
  #+begin_src emacs-lisp
    (package-initialize)
    (add-to-list 'package-archives
	  '("melpa" . "https://melpa.org/packages/") t)
  #+end_src

  to your initialisation file.  Activate this code (for example by
  restarting Emacs), then type `M-x install-package', answer the
  prompt with "apdl-mode" and conclude this command with <RET>.

  (You might also install it with GNU-Emacs' package interface `M-x
  list-packages', find `apdl-mode', mark it with `i' and install it
  with `x'.)

   If you prefer the stable package archive instead of the development
   versions, exchange above package source with
   #+begin_src emacs-lisp
      (add-to-list 'package-archives
      '("melpa-stable" . "https://stable.melpa.org/packages/") t)
   #+end_src

* Manual Installation
  - Download a released tar package from the [[https://github.com/dieter-wilhelm/apdl-mode2/releases/][APDL-mode release page]] -
    under the section "Assets".
  - Install the package within Emacs: Please type `M-x
    package-install-file <RET>' and select your downloaded tar file.

  # That's it. Really what about require 'apdl-mode?

  *Hint:* If you are getting an error message "package.el is not yet
  initialised", you are using Emacs' packaging system for the first
  time.  It is necessary to initialise this machinery once, please
  type: `M-: (package-initialize) <RET>' (it's an `ALT + :', a colon!)
  and then apply `M-x package-install-file <RET>' again.

* Development and Source Code Installation
  Please clone the APDL-Mode git archive in a directory of your
  choice:
  #+BEGIN_SRC sh
    git clone https://github.com/dieter-wilhelm/apdl-mode2.git
  #+END_SRC

  Or download the GitHub ZIP archive (press the `Code' button:
  Download ZIP), extract the sources to some folder and add the
  following elisp lines to your Emacs initialisation file:
  #+BEGIN_SRC elisp
    ;; the source directory must first be set in the `load-path' variable
    (add-to-list 'load-path  "/your/folder/with/apdl-mode/")
    (require 'apdl-mode)
  #+END_SRC
